### ISSUE TITLE
[Question] Progress? ETA?

### ISSUE THREAD

**Issue by yodaluca23** [mon5termatt/medicat_updater#2]
This would be a really awesome script! But I notice their hasn't been any newer than 10 months ago... Do you still plan on developing this? If so is their any ETA?

**Comment by yodaluca23** [comment]
The logic for it shouldn't be that hard, it would just hash the USB, like it already does after installation, but with the latest hash file, if it finds ones missing or changed, then download those ones, and add them where they need to be, or replace them where they need to be, then probably want to hash it again... Simple logic, I have no idea how difficult to code though, some sort of ETA would be nice though...

**Comment by mon5termatt** [comment]
*eventually*
